apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-fight-config
data:
  DB_CONFIG_HOST: {{ .Values.config.DB_CONFIG_HOST | quote }}
  DB_CONFIG_PORT: {{ .Values.config.DB_CONFIG_PORT | quote }}
  KAFKA_BROKER: {{ .Values.config.KAFKA_BROKER | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  MINIO_ROOT_USER: {{ .Values.config.MINIO_ROOT_USER | quote }}
