apiVersion: v1
kind: Secret
metadata:
  name: bao-fight-secrets
type: Opaque
data:
  # Helm сам переведет строку в base64
  DB_CONFIG_USER: {{ .Values.secrets.DB_CONFIG_USER | b64enc | quote }}
  DB_CONFIG_PASSWORD: {{ .Values.secrets.DB_CONFIG_PASSWORD | b64enc | quote }}
  DB_CONFIG_DBNAME: {{ .Values.config.DB_CONFIG_DBNAME | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.MINIO_ROOT_PASSWORD | b64enc | quote }}
